name: Deploy All-Tests Dashboard to GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies for all-tests
        run: |
          cd all-tests
          npm install

      - name: Build all projects
        run: |
          cd all-tests
          npm run build

      - name: Prepare deployment
        run: |
          # Create deployment directory
          mkdir -p deploy

          # Copy all-tests dist to deploy/all-tests
          cp -r all-tests/dist deploy/all-tests

          # Copy root index.html to deploy root
          cp index.html deploy/

          # Create a simple 404 page
          echo '<!DOCTYPE html><html><head><title>404 - Page Not Found</title></head><body><h1>404 - Page Not Found</h1><p><a href="/">Go to Dashboard</a></p></body></html>' > deploy/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./deploy"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
